2017-08-21 21:16:05.635567: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 21:16:05.637911: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-21 21:16:05.637923: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Using TensorFlow backend.
/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/keras/models.py:258: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
Traceback (most recent call last):
  File "task_space.py", line 111, in <module>
    f = plt.figure(figsize=(30,12))
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
Using TensorFlow backend.
/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/keras/models.py:258: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
task_space.py:104: RuntimeWarning: invalid value encountered in true_divide
  reuse = np.sum(abs(coef[target_col_index]))/sum(abs(coef))
Traceback (most recent call last):
  File "task_space.py", line 111, in <module>
    f = plt.figure(figsize=(30,12))
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/home/ieisenbe/miniconda3/envs/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
